### ISSUE TITLE
希望对话泡泡中的两个不同角色的对话框能够一左一右地显示。

### ISSUE THREAD

**Issue by pimgeek** [mindpin/chatflow#10]
@ben7th 如下图所示。

![](http://img.teamkn.com/i/qjHVXdZn.png)

如果是三个或三个以上的角色，那么暂且设定只有一个角色在左，其余都在右。

**Comment by ben7th** [comment]
增加了两个参数设置来支持这一体验：

---

NPC 的设置：

``` yaml
npcs:
  - id: android
    name: ANDROID机器人
    avatar: http://img.teamkn.com/i/tLsGEwZz.png
    direction: right
```

增加了 direction 参数，来控制 NPC 对话泡泡的方向。（对话泡泡方向，特指对话泡泡的小三角尖儿指向的方向）

默认 direction 为 left （该 NPC 的所有对话泡泡指向左，头像在左）

可以设置 direction right （该 NPC 的所有对话泡泡指向右，头像在右）

---

对话泡泡的设置：

``` yaml
  - npc: ben7th
    sentences:
    - text: 所以说，这样来展示文字是比单纯的文本要生动的。
    direction: right
```

对话泡泡上可以设置 direction 参数来单独控制该对话泡泡的方向（而无论该对话泡泡的 NPC 方向如何设置）

默认 direction 为 left （该对话泡泡的所有对话泡泡指向左，头像在左）

可以设置 direction right （该对话泡泡的所有对话泡泡指向右，头像在右）
