### ISSUE TITLE
第 7 点：在这种情况下，自动滚屏功能未能正常工作

### ISSUE THREAD

**Issue by pimgeek** [mindpin/chatflow#7]
脚本最末尾的图片，因为自动滚屏功能未能正常工作，没有自动显示出来。
测试用显示模式：Chrome 移动端模拟器 Nexus 5 以及 Nexus 7
重现脚本如下：

``` yaml
npcs:
  - id: ma
    name: 小马老师
    avatar: http://img.teamkn.com/i/uK49MJ9E.png@100w_100h_1e_1c.png
  - id: qu
    name: 问号同学
    avatar: http://img.teamkn.com/i/D01dg9Lj.png@100w_100h_1e_1c.png

scripts:
  # 第九，引出搜索要求的逻辑关系问题
  - npc: ma
    sentences:
    - text: 利用 AOL Search 的逻辑操作，还可以实现更细致的搜索效果。
      speed: 20
      linebreak: false
      delay: 500
    - text: 请问号同学来猜一猜，接下来的这一次搜索动作，能达到怎样的效果？
      speed: 20
      delay: 600
  - npc: qu
    sentences:
    - text: 好啊~ 我试试看。
      speed: 20
    clear: false
  - npc: ma
    sentences:
    - text: 小马老师在 AOL Search 的输入框里写下了这样一段内容：
      speed: 20
      style:
        display: block
        margin-bottom: 16px
      delay: 400
    - text: 谣言 传言 site:guokr.com
      speed: 20
      style:
        display: block
        border: 1px solid silver
        border-radius: 5px
        padding: 1%
      delay: 600
    clear: false
  - select: search-syntax-logic-and
    text: 关于搜索结果列表中的文章，下面那个判断是正确的？
    items:
      - 必须同时含有“谣言”和“传言”。
      - 至少包含“谣言”或“传言”中的一个。
    clear: false
  - selected: search-syntax-logic-and
    response:
      - npc: ma
        sentences:
        - text: 恭喜~ 回答正确，加十分！
          speed: 20
          delay: 600

        clear: false
      - npc: ma
        sentences:
        - text: 很遗憾的说，答错了…… 
          speed: 20
          delay: 600

        clear: false
    clear: false
  - npc:
    sentences:
    - image: http://img.teamkn.com/i/VmH6Pt1C.png@500w.png
    clear: false
```

**Comment by pimgeek** [comment]
再补充一个例子，仍然是最后的图片无法自动显示：

``` yaml
npcs:
  - id: ma
    name: 小马老师
    avatar: http://img.teamkn.com/i/uK49MJ9E.png@100w_100h_1e_1c.png
  - id: qu
    name: 问号同学
    avatar: http://img.teamkn.com/i/D01dg9Lj.png@100w_100h_1e_1c.png

scripts:
  # 第十三，教程收尾工作
  - npc: ma
    sentences:
    - text: 可以用来操纵搜索引擎的使用技巧有很多，我们今天只讲了最基础的。
      speed: 20
      linebreak: false
      delay: 400
    - text: 如果前面讲到的搜索技巧大家都已理解，并亲自操作过一遍，就算入门了。
      speed: 20
      delay: 800
  - npc: qu
    sentences:
    - text: 到这里就要结束了吗？可我还想多学两招哪！
      linebreak: false
      speed: 20
    clear: false
  - npc: ma
    sentences:
    - text: 没问题啊，早就猜到问号同学是不会满足于入门水平的！
      speed: 20
      linebreak: false
      delay: 800
    - text: 请访问下面这个网址，以便了解更多的搜索技巧。
      speed: 20
      linebreak: false
      delay: 800
    - text: 从谷歌搜获更多
      speed: 20
      link: http://s.4ye.me/qEDN38
      style:
        font-size: 120%
        font-weight: bold
      delay: 800
    - image: http://img.teamkn.com/i/jwsiE9Ls.png@500w.png
    clear: false
```
